name: YC Node.js Functions CI/CD Pipeline

on:
  push:
    branches: [master, shorten, delete]
  workflow_dispatch:

jobs:
  build:
    name: Build and Compile
    runs-on: ubuntu-latest
    outputs:
      build-dir: ${{ steps.set-output.outputs.build-dir }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare distribution files
        run: |
          mkdir -p dist
          cp package.json dist/
          cp -r src/*.js dist/
          [ -f key.json ] && cp key.json dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/

  archive:
    name: Create Deployment Package
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, shorten, delete]
        include:
          - branch: master
            zip_name: redirect.zip
          - branch: shorten
            zip_name: create.zip
          - branch: delete
            zip_name: delete.zip
    if: github.ref == format('refs/heads/{0}', matrix.branch)

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist/

      - name: Create ZIP archive
        run: |
          mkdir -p build
          cd dist && zip -r "../build/${{ matrix.zip_name }}" . -x "*node_modules*"

      - name: Upload ZIP package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.zip_name }}
          path: build/${{ matrix.zip_name }}

  deploy:
    name: Deploy Function
    needs: archive
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [master, shorten, delete]
        include:
          - branch: master
            zip_name: redirect.zip
            function_name: redirect-func
          - branch: shorten
            zip_name: create.zip
            function_name: create-func
          - branch: delete
            zip_name: delete.zip
            function_name: delete-func
    if: github.ref == format('refs/heads/{0}', matrix.branch)

    steps:
      - name: Download ZIP package
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.zip_name }}
          path: build/

      - name: Deploy to Yandex Cloud
        uses: yc-actions/yc-sls-function@v1.0.1
        with:
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: ${{ matrix.function_name }}
          runtime: 'nodejs16'
          memory: '256Mb'
          execution-timeout: '5s'
          source-path: ./build/${{ matrix.zip_name }}
          service-account-id: ${{ secrets.SERVICE_ACCOUNT_ID }}
          entrypoint: 'index.handler'
          environment: |
            DATABASE=${{ secrets.DB_NAME }}
            ENDPOINT=${{ secrets.DB_ENDPOINT }}
